### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Jakee8718** [Hazza3100/Instagram-Aio#3]
the follows dont work for some reason. Im doing "python mainy.py" and it runs but when i enter the followers it says it works but then it doesnt go to my account. Do I need some sort of proxies or something? Please help.

**Comment by Hazza3100** [comment]
Doesn't work? Maybe add some cookies.

**Comment by Itamar1337** [comment]
maybe don't do mainy.py when its called main.py 🤡

**Comment by Jakee8718** [comment]
> maybe don't do mainy.py when its called main.py 🤡

LMFAO u dont know python

**Comment by Hazza3100** [comment]
Neither do u by the looks of things

**Comment by Itamar1337** [comment]
> Neither do u by the looks of things

for the protocol I do know python (:

**Comment by Jakee8718** [comment]
true but i know how to run it

**Comment by Hazza3100** [comment]
> > Neither do u by the looks of things
> 
> 
> 
> for the protocol I do know python (:

Ik you was helping..
