### ISSUE TITLE
Problems with argument 'username'

### ISSUE THREAD

**Issue by ElMarcho04** [Hazza3100/Instagram-Aio#5]
Traceback (most recent call last):
  File "main.py", line 165, in <module>
    x.main()
  File "main.py", line 132, in main
    user_id = aio.get_id(username)
TypeError: get_id() missing 1 required positional argument: 'username'

**Comment by Jakee8718** [comment]
it cant fetch the username

**Comment by Hazza3100** [comment]
> 

Valid username?
